### ISSUE TITLE
Update template to display deprecation messages more prominently

### ISSUE THREAD

**Issue by alicejli** [googleapis/jsdoc-fresh#67]
Currently if a method is deprecated, the deprecation message is generated below the "Returns" table, and if a service is deprecated, the deprecation message is generated below the "Parameters" table, which is easy to miss. For example:

Deprecated service (currently):

![Untitled drawing](https://user-images.githubusercontent.com/65933803/120543200-e8a14980-c3a0-11eb-92e9-6457485797c7.png)

Deprecated method (currently):

![DeprecatedMethodCurrent](https://user-images.githubusercontent.com/65933803/120543382-1be3d880-c3a1-11eb-8c6f-ba5782a15c30.png)

Ideally, the deprecation message should feature more prominently at the top, like this:

Deprecated service (ideal):

![DeprecatedServiceNew](https://user-images.githubusercontent.com/65933803/120543799-93b20300-c3a1-11eb-9d26-404f44f06d57.png)

Deprecated method (ideal):

![DeprecatedMethodNew](https://user-images.githubusercontent.com/65933803/120543819-97de2080-c3a1-11eb-9e26-0e30e06e32ea.png)

**Comment by SurferJeffAtGoogle** [comment]
Please provide links to the screens you snapshotted here.

**Comment by SurferJeffAtGoogle** [comment]
Nevermind.  I see your pull request.  Looks good.
